app:
  name: springboot-jwt-demo

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: queenvictoria

#使用自动配置的内存H2数据库
# 后端Spring-boot会跑在端口 8080
# 有两个账户预设在内存:
# - User - user:123
# - Admin - admin:123
# *******启动服务访问 ip:8080 体验服务
#----
#真正的数据库
#spring:
#  jpa:
#    hibernate:
#      # possible values: validate | update | create | create-drop
#      ddl-auto: create-drop
#  datasource:
#    url: jdbc:mysql://localhost/myDatabase
#    username: myUser
#    password: myPassword
#    driver-class-name: com.mysql.jdbc.Driver
